### ISSUE TITLE
How to cretae a human?

### ISSUE THREAD

**Issue by tgrmev** [Unity-Technologies/com.unity.cv.synthetichumans#1]
Hello, I tried to manage to add a human while using your repository but I could not be succesfull. I could not find any educational stuff how to use your package on Youtube or your folder read.me. Could you share a sample prefab or explain how can the user create a human? Thanks

**Comment by csun** [comment]
Hey there - I see you've closed this issue, but in case you didn't find it, [here](https://github.com/Unity-Technologies/com.unity.cv.synthetichumans/wiki/Synthetic-Humans-Tutorial) is the link to our intro tutorial. There was a broken link in the readme, which I've fixed (thanks for bringing it up).

In general, all the docs for this project will be in the [github wiki](https://github.com/Unity-Technologies/com.unity.cv.synthetichumans/wiki).
