### ISSUE TITLE
Save synthetic humans locally as a prefab and repurpose it

### ISSUE THREAD

**Issue by cjerry1243** [Unity-Technologies/com.unity.cv.synthetichumans#13]
Hi, 

Thank you all for the fantastic work!

The HumanGenerationRandomizer is a runtime randomizer. I am wondering if there is a correct way to run it and save the randomly generated humans as a prefab and repurpose it.
I tried to do this but the mesh is missing.

@csun

**Comment by csun** [comment]
Hey Jerry, sorry for the late reply.

This sort of usage is unfortunately not supported due to the way that mesh and material generation works. I don't think it will be possible to accomplish what you are attempting.
