### ISSUE TITLE
Map AnthroNet mesh vertices to SMPL mesh

### ISSUE THREAD

**Issue by Henistein** [Unity-Technologies/com.unity.cv.synthetichumans#16]
Is there any way to map the vertices from the generated meshes (AnthoNet meshes) to the base SMPL mesh? 

I need to make semantic segmentation by parts (head, torso, hands, arms, legs...), and need a way to make the mapping. Or if there is already some method to make this segmentation let me know.

**Comment by salehe-ee** [comment]
Thank you for your interest in this work. We are not able to provide that mapping for you due to the compliance with SMPL's license policies.
