### ISSUE TITLE
Dead link in tutorial page

### ISSUE THREAD

**Issue by hukaidong** [Unity-Technologies/com.unity.cv.synthetichumans#17]
In paragraph:

> The Synthetic Humans package relies on the [Unity Perception Package](https://github.com/Unity-Technologies/com.unity.perception) to facilitate human generation and randomization. Thus, if you are not already familiar with the Perception package, we strongly recommend completing the [main tutorial](https://github.com/Unity-Technologies/perception/blob/main/com.unity.perception/com.unity.perception/Documentation~/Tutorial/TUTORIAL.md) and the [human labeling tutorial](https://github.com/Unity-Technologies/perception/blob/main/com.unity.perception/com.unity.perception/Documentation~/HumanPose/TUTORIAL.md) offered with the Perception package before diving into Synthetic Humans.

Both tutorial link go to 404 pages.

**Comment by csun** [comment]
Thanks, should be fixed.
