### ISSUE TITLE
Advanced Placement Tutorial - Action Item Issue

### ISSUE THREAD

**Issue by AlexBedardReidU3D** [Unity-Technologies/com.unity.cv.synthetichumans#18]
[Page with Issue](https://github.com/Unity-Technologies/com.unity.cv.synthetichumans/wiki/Advanced-Placement-Tutorial)

### The section: 

> 🟢 Add a NavMesh Modifier component to the Floor object and make sure Area is set to NavMesh Modifier.
> 
> 🟢 Enable Override Area and set the Area Type to Walkable.
> 
> 🟢 Add a Ground Placer Tag component to the Floor object.
> 
> 🟢 You can now bake a test NavMesh to confirm that the correct settings have been applied.

<img width="649" alt="image" src="https://github.com/Unity-Technologies/com.unity.cv.synthetichumans/assets/114178283/99de700a-1918-405e-a388-e6f701a8e94b">

### Should read:
> 🟢 Add a NavMesh Modifier component to the Floor object .
> 
> 🟢 Enable Override Area and set the Area Type to Walkable.
> 
> 🟢 Add a Ground Placer Tag component to the Floor object and make sure Area is set to NavMesh Modifier.
> 
> 🟢 You can now bake a test NavMesh to confirm that the correct settings have been applied.

**Comment by csun** [comment]
Thanks, fixed
