### ISSUE TITLE
Description of the synthetic human assets

### ISSUE THREAD

**Issue by cjerry1243** [Unity-Technologies/com.unity.cv.synthetichumans#19]
Hi,

Thanks for the great work.
I currently working on a publication that is built on top of synthetic humans.
It would be helpful if a description of the assets is provided. (Basically how many or what are the choices of clothing, hair styles, face VAT?) 

I didn't see it in the AnthroNet paper either.

**Comment by csun** [comment]
Hey Jerry,

Unfortunately, we don't have any sort of count like that available. I spoke to the AnthroNet team and I don't think they tracked those metrics either. My best suggestion would be to write a script to count for yourself.

In the `Resources/_Assets` folder, you'll see a file named `DefaultAssetPack`. This should contain a reference to every single asset .taginfo file that is used to generate humans. From each of those .taginfo files you should be able to derive information about the asset (eg. if a tag is a `Clothing` it tells you that the related asset is a piece of clothing, and its `ClothingElement` field will tell you whether it's pants, shoes, a shirt, etc.). If you write a script with all of this logic and iterate through the entire `DefaultAssetPack`, you should be able to get the counts you're looking for.

I'd also be very interested in reading your paper when it's ready. If you're open to sharing it, please feel free to get in touch with me at cameron.sun@unity3d.com :)
