### ISSUE TITLE
Human asset loading file

### ISSUE THREAD

**Issue by RRuschel** [Unity-Technologies/com.unity.cv.synthetichumans#2]
Hello,

I'm pretty new to Unity and I'm trying to generate some small dataset containing humans. I have installed `perception 1.0.0-preview.1` together with `synthetichumans` with tag `CS3199`, everything seemed to go well as there were no errors during installation, the process took a long time as stated in the tutorial, and the appropriate folder inside PackageCache is 9.6Gb.
However, when I hit play to run the scenario provided inside the Samples, I get 999+ of the following error:

Human asset loading failed: Could not load tag linked asset of type Texture2D. Check asset tag names VAT.XX.XXXX.XX.XX.XX.XX.XXXX

I checked those VAT files and they exist inside the package folder, they have normal read and write permissions (I can even open the .exr ones on other software).

Below are screenshots of the error during runtime and the Inspector view of one VAT file

[Error screenshot](https://imgur.com/a/3pMmiUN) 

Any idea what might be causing this issue?

Thanks for the great work BTW!

**Comment by csun** [comment]
Hey there! A couple suggestions:

1. In the project / file browser tab in your unity project, go to the folder named "Packages" and look for the synthetichumans package. Right click it and select "Reimport". It'll process for a while, but when it finishes the errors should hopefully be gone.
2. If that doesn't work, check that [git lfs](https://git-lfs.com/) is installed. If not, there's a chance that the meshes were not properly downloaded with the rest of the package.
3. If git LFS _is_ installed, I would go and manually check that the meshes are properly downloaded. In the project / file browser tab in your unity project, go to the folder named "Packages" and look for the synthetichumans package. Then, look for a mesh file (eg. the one at `Resources/_Assets/system/Clothing/01/0000/Models/01/Mesh.01.0000.01.01.0000.fbx`). When you click on this, the inspector tab should show a preview of some sort of mesh. If it's corrupted or whatnot, it will say so. This probably indicates that your git lfs installation is not being used by whatever version of git that Unity used to pull down the package.

Please let me know if that does / does not help you fix your issue!

**Comment by RRuschel** [comment]
Hi,

The first suggestion worked out! I reimported the library and the simulations are running fine now, just getting a few warnings that some meshes reached the maximum polygon limit, but that should be fine!

**Comment by csun** [comment]
Glad to hear it worked! The max polygon limit warning is harmless, albeit annoying.

I'm gonna close this issue for now! Please reach out if you need any help.
