### ISSUE TITLE
AnthroNet code and Are SyntheticHumans meshes == AnthroNet meshes

### ISSUE THREAD

**Issue by m-junaida** [Unity-Technologies/com.unity.cv.synthetichumans#20]
Hi, 
I read the AnthroNet paper, and said its available on GitHub. But, I couldn't find that. 
Can you help me where can i find the codebase?

Also, If I generate meshes from SyntheticHumans. Where or How can I find or get the mapping from mesh -> anthropometric measurements?
And if I have anthropometric measurements Where can i find the tutorial to generate 3d mesh using these?

Thanks in advance. Really interesting work done in Anthronet!

**Comment by salehe-ee** [comment]
Thank you for your interest in this work. Yes, the Synthetic Humans meshes are the AnthroNet meshes. Currently we are not offering the measurements feature. However by referring to our paper, and the Unity Perception package documentation, you may be able to replicate the measurements.
