### ISSUE TITLE
How to create a hand?

### ISSUE THREAD

**Issue by yayayru** [Unity-Technologies/com.unity.cv.synthetichumans#5]
Hello! I'd like to manage to add different hand shapes and hand orientations. Is there a possibility?

**Comment by csun** [comment]
Hello there - in terms of orientation, the humans have fully articulated hands. You can search on sites like [Mixamo](https://www.mixamo.com/#/?page=1&type=Motion%2CMotionPack) for hand animations to apply  (or make your own), then follow [our tutorial](https://github.com/Unity-Technologies/com.unity.cv.synthetichumans/wiki/Synthetic-Humans-Tutorial) for setting up an animation randomizer. 

In terms of different hand shapes, that's unfortunately not currently possible. We have no plans to implement this either (the whole project is essentially unmaintained). Humans will randomly generate with bigger / smaller / different colored hands, but that's all the variation we can manage.

I'm going to close this issue for now, but feel free to reply if you have any other questions.
