### ISSUE TITLE
IS THE PACKAGE COMPATIBLE WITH THE STANDARD PIPELINE?

### ISSUE THREAD

**Issue by OculusQuestVR** [Unity-Technologies/com.unity.cv.synthetichumans#6]
Dear all, I make apps for Oculus Quest which for obvious reasons is bound to use the Standard pipeline or at most URP. The perception package and the synthetic Humans package are somewhat compatible with the STANDARD pipeline. I would be interested in using them in my projects. Thanks in advance for all those who will send me useful information Mauro

**Comment by csun** [comment]
Hey Mauro,

We've unfortunately never tested this library with anything but HDRP, so I can't answer this for sure. However, I'm pretty sure that the materials we use for the humans depend on some HDRP-specific features. I think it's unlikely that it would work with any other render pipeline, and we have no plans to support that use case, either.

If you want to verify for yourself, though, it would be pretty quick to create a URP project and try loading in this package. I wouldn't even bother with the standard pipeline, though.

Best of luck!

**Comment by OculusQuestVR** [comment]
Dear Cameron, thank you very much for your reply, I'm only reading your
message now, I'll definitely try.

 Greetings

 Mauro

Il Gio 16 Mar 2023, 17:54 Cameron Sun ***@***.***> ha scritto:
