### ISSUE TITLE
commercial license

### ISSUE THREAD

**Issue by smidm** [Unity-Technologies/com.unity.cv.synthetichumans#7]
The project has now non-commercial / academic research type license. Do you plan to have an option for commercial use?

**Comment by csun** [comment]
Hello, Matěj. We have licensed the package to a few commercial clients on a paid basis, but I don't think we have a standardized process in place yet for doing so.

Is that something you'd be interested in learning more about? If so, I can try to get you in touch with the right people.

**Comment by smidm** [comment]
It is not our immediate need, but good to know that there is the option.

**Comment by csun** [comment]
Sounds good, I'll close this issue for now. If you need to get in touch, my email address is firstname dot lastname at unity3d.com
