### ISSUE TITLE
How to generate a human character with different clothes?

### ISSUE THREAD

**Issue by YunjiePeng** [Unity-Technologies/com.unity.cv.synthetichumans#9]
Hello, it is greatly appreciated for your wonderful work in promoting the development of computer vision. 

Can I generate a human with different clothes based on com.unity.cv.synthetichumans? (e.g., human A with clothes B, human A with clothes C, human A with clothes D, etc.). Is there a possibility?

I have checked the original script file and found that the clothing is controlled by "generationAssetRefs.clothingTags". Any idea for building the customized HumanGenerationRandomizer? Would you please provide a sample file to support the need for cloth changing to boost recognition tasks in computer vision?

**Comment by csun** [comment]
Hey Yunjie, just wanted to clarify what you're asking:

It sounds like you want to be able to regenerate the same exact human body / face but only change their clothing. Is that a correct interpretation?

**Comment by YunjiePeng** [comment]
Hi Cameron, what you interpreted is exactly what I want.

Actually, I have found the class [HumanGenerator](https://github.com/Unity-Technologies/com.unity.cv.synthetichumans/blob/c40da94dfcfb7afae0738f629e34584a6d53dc02/Runtime/HumanGenerator.cs) which contains functions named "ReviewAndAssignClothingTags" and "GenerateClothes", where clothingTags are randomly generated and corresponding clothing items are created.

Therefore, I try to write a new class similar to "HumanGenerator" to provide a public function for changing clothes on a human (i.e., instantiated from generationConfig.basePrefab). 

Here comes a question when new clothes are generated, the previous old clothes still exit. How can I remove the old clothes and some repeated generated "root"? Is there a way to get old clothes and delete them during the generation of different clothes on the same human body?

**Comment by YunjiePeng** [comment]
The screenshot is pasted as follows.
![WechatIMG1991](https://github.com/Unity-Technologies/com.unity.cv.synthetichumans/assets/67147416/0d441d03-f516-4031-97d8-98675784f64e)

**Comment by YunjiePeng** [comment]
Thanks a million to your wonderful work, I have finally realized it by customizing my own "HumanGenerator". The framework of Synthetic Human is well-designed and easy to use for building customized dataset.

Old clothes can be easily removed by "transform.Find()" and "Object.DestroyImmediate()".

**Comment by csun** [comment]
Glad you found a solution, and thanks for your kind words!
